#!/bin/bash

PORT=8888

export LOCAL_USER_ID=`id -u $USER`
export LOCAL_GROUP_ID=`id -g $USER`
export LOCAL_GROUP_NAME=`id -gn $USER`
DOCKER_USER_ARGS="--env LOCAL_USER_ID --env LOCAL_GROUP_ID --env LOCAL_GROUP_NAME"

docker run --rm -p $PORT:8888 -p 6000:6000 -p 7000:7000 \
    $DOCKER_USER_ARGS --privileged \
    --mount type=bind,source="$(pwd)"/scripts/start-jupyter.sh,target=/usr/local/bin/start-jupyter.sh \
    --mount type=bind,source="$(pwd)"/notebooks,target=/home/exotica/notebooks \
    vladimirivan/exotica-notebook:latest

